server:
  port: 8081

spring:
  application:
    name: ravius-whatsapp-bot
  datasource:
    url: ${SUPABASE_URI}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  data:
    redis:
      host: evolution-redis
      port: 6379
      password: "!Yuji40028922!"
      timeout: 60000
      database: 1


kind: Application

evolution:
  api:
    url: ${EVOLUTION_API_URL:http://localhost:8080}
    api-key: ${EVOLUTION_API_KEY:your-api-key-here}

allowed:
  test-numbers: ${ALLOWED_TEST_NUMBERS}